
configfile: "config/config.yaml"

SAMPLES = config["samples"]
REF_FASTA = config["refFasta"]
CHUNK_DIR = config["chunkDir"]
CHUNK_PREFIX = config["chunkPrefix"]
CHUNKS   = range(1, config["nChunks"] + 1)
REP      = range(1, config["nReps"] + 1)
MIN_DP   = config["minDP"]
BAM_DIR  = config["bamDir"]

################################################

rule all:
    input:
        expand(
            "results/filtered/{samp}.chunk{chunk}.mpileup.rep{repi}.DP_{min_dp}.vcf.gz",
            samp=SAMPLES,
            chunk=CHUNKS,
            repi=REP,
            min_dp=MIN_DP,
        ),
        expand(
            "results/filtered/{samp}.chunk{chunk}.mpileup.rep{repi}.DP_{min_dp}.vcf.gz.csi",
            samp=SAMPLES,
            chunk=CHUNKS,
            repi=REP,
            min_dp=MIN_DP,
        )

include: "workflow/rules/calling.smk"
