import pandas as pd

configfile: "config/config.yaml"

SV_VCF = config["svVcf"]
VCF_DIR = config["vcfDir"]
SAMPLES = pd.read_csv(config["popFile"], sep="\t").iloc[:,0].tolist()
CHUNK_DIR = config["chunkDir"]
CHUNK_PREFIX = config["chunkPrefix"]
CHUNKS   = range(1, config["nChunks"] + 1)
REP      = range(1, config["nReps"] + 1)

rule all:
    input:
        expand("results/snp_patt/merged.chunk{chunk}.mpileup.rep{repi}.DP_{min_dp}.patt_counts.w_250kb.tsv",
            chunk=CHUNKS,
            repi=REP,
            min_dp=config["sampleSnpPatterns"]["minDP"]
        ),
        expand("results/missingness/merged.chunk{chunk}.mpileup.rep{repi}.DP_{min_dp}.missingness.w_250kb.tsv",
            chunk=CHUNKS,
            repi=REP,
            min_dp=config["sampleSnpPatterns"]["minDP"]
        ),
        expand(
            "results/svs_patt/svs.rep{repi}.SVLEN_{min_svlen}.patt_counts.w_250kb.tsv",
            repi=REP,
            min_svlen=config["sampleSvPatterns"]["minSVLEN"]
        )

include: "workflow/rules/analysis.smk"
